name: flutter_application_4
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: any

  flutter_gen: ^3.0.0
  flutter_login: ^4.0.0
  flutter_form_builder: ^7.8.0
  sqflite: ^2.2.8+4
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/
   

