// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxSyS7QYfh-rSdHUn8AZOD0P2yhGkqDII',
    appId: '1:227635192903:web:58afad0bafb95e95ab3d62',
    messagingSenderId: '227635192903',
    projectId: 'teacher-app-b1621',
    authDomain: 'teacher-app-b1621.firebaseapp.com',
    storageBucket: 'teacher-app-b1621.firebasestorage.app',
    measurementId: 'G-4ZCTZ1PCL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGV5Fnm_N0SwlaJvcZYNtZGglvABHGHig',
    appId: '1:227635192903:android:d80ee36068d1204fab3d62',
    messagingSenderId: '227635192903',
    projectId: 'teacher-app-b1621',
    storageBucket: 'teacher-app-b1621.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5PbOBW29iMIALEBhoWMiLfb97gCdxTzQ',
    appId: '1:227635192903:ios:a13037c8ea65e76dab3d62',
    messagingSenderId: '227635192903',
    projectId: 'teacher-app-b1621',
    storageBucket: 'teacher-app-b1621.firebasestorage.app',
    iosBundleId: 'com.example.teacharApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5PbOBW29iMIALEBhoWMiLfb97gCdxTzQ',
    appId: '1:227635192903:ios:a13037c8ea65e76dab3d62',
    messagingSenderId: '227635192903',
    projectId: 'teacher-app-b1621',
    storageBucket: 'teacher-app-b1621.firebasestorage.app',
    iosBundleId: 'com.example.teacharApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxSyS7QYfh-rSdHUn8AZOD0P2yhGkqDII',
    appId: '1:227635192903:web:7f112960fca34223ab3d62',
    messagingSenderId: '227635192903',
    projectId: 'teacher-app-b1621',
    authDomain: 'teacher-app-b1621.firebaseapp.com',
    storageBucket: 'teacher-app-b1621.firebasestorage.app',
    measurementId: 'G-3C1J9GRKCE',
  );
}
